require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - config/**/*
    - bin/**/*
    - vendor/**/*
    - db/schema.rb

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
