default: &default
  adapter: postgresql
  username: postgres
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'secret' } %>
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  timeout: 5000

development:
  <<: *default
  database: perfumistiq_development

test:
  <<: *default
  database: perfumistiq_test

production:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] || 'perfumistiq_production'  %>
